# -------
# Enabled
# -------

# 64-bit file offsets
VERSION_CFLAGS += -D_FILE_OFFSET_BITS=64
CUSTOM_C_DEFINES += -D_FILE_OFFSET_BITS=64

# No segmented memory
VERSION_CFLAGS += -DNO_SEGMENTED_MEMORY
CUSTOM_C_DEFINES += -DNO_SEGMENTED_MEMORY

# Widescreen
VERSION_CFLAGS += -DWIDESCREEN
CUSTOM_C_DEFINES += -DWIDESCREEN

# Options menu
EXT_OPTIONS_MENU := 1
VERSION_CFLAGS += -DEXT_OPTIONS_MENU
CUSTOM_C_DEFINES += -DEXT_OPTIONS_MENU

# Better cam/Puppy cam
BETTERCAMERA := 1
VERSION_CFLAGS += -DBETTERCAMERA
CUSTOM_C_DEFINES += -DBETTERCAMERA

# Cheats
CHEATS_ACTIONS := 1
VERSION_CFLAGS += -DCHEATS_ACTIONS
CUSTOM_C_DEFINES += -DCHEATS_ACTIONS

# No drawing distance
NODRAWINGDISTANCE := 1
VERSION_CFLAGS += -DNODRAWINGDISTANCE
CUSTOM_C_DEFINES += -DNODRAWINGDISTANCE

# External data
EXTERNAL_DATA := 1
VERSION_CFLAGS += -DEXTERNAL_DATA -DFS_BASEDIR="\"$(BASEDIR)\""
CUSTOM_C_DEFINES += -DEXTERNAL_DATA -DFS_BASEDIR="\"$(BASEDIR)\""

# Smoke texture fix
TEXTURE_FIX := 1
VERSION_CFLAGS += -DTEXTURE_FIX
CUSTOM_C_DEFINES += -DTEXTURE_FIX

# Check custom skyboxes
ifeq ($(or $(and $(wildcard textures/skyboxes/Skybox_Rules.ld),1),0),1)
  VERSION_CFLAGS += -DOMM_HAS_CUSTOM_SKYBOXES=1
  CUSTOM_C_DEFINES += -DOMM_HAS_CUSTOM_SKYBOXES=1
else
  VERSION_CFLAGS += -DOMM_HAS_CUSTOM_SKYBOXES=0
  CUSTOM_C_DEFINES += -DOMM_HAS_CUSTOM_SKYBOXES=0
endif

# --------
# Disabled
# --------

# Built-in debug menu
EXT_DEBUG_MENU := 0

# Built-in extended bounds
EXTENDED_BOUNDS := 0

# Built-in frame interpolation
HIGH_FPS_PC := 0

# No rumble
RUMBLE_FEEDBACK := 0

# No Goddard
GODDARD_MFACE := 0

# No Discord RPC
DISCORDRPC := 0

# No textsaves
TEXTSAVES := 0

# No extra QoL
VANILLA_CHECKS := 0
QOL_FIXES := 0
QOL_FEATURES := 0
QOL_REDONE := 0
TOUCH_CONTROLS := 0

# ------
# Custom
# ------

# Debug
ifeq ($(DEBUG),1)
  VERSION_CFLAGS += -DDEBUG
  CUSTOM_C_DEFINES += -DDEBUG
  COMPILER_OPT := debug
endif

# Mouse (no DirectX yet)
ifneq ($(WINDOW_API),DXGI)
  CUSTOM_C_DEFINES += -DMOUSE_ACTIONS
endif

# CLI
ifeq ($(COMMAND_LINE_OPTIONS),1)
  CUSTOM_C_DEFINES += -DCOMMAND_LINE_OPTIONS
endif

# MOP
ifeq ($(PORT_MOP_OBJS),1)
  CUSTOM_C_DEFINES += -DPORT_MOP_OBJS
endif

# OMM Debug menu
OMM_DEBUG ?= -1
ifneq ($(OMM_DEBUG),-1)
  VERSION_CFLAGS += -DOMM_DEBUG=$(OMM_DEBUG)
  CUSTOM_C_DEFINES += -DOMM_DEBUG=$(OMM_DEBUG)
endif

# OMM Dev features
OMM_DEV ?= -1
ifneq ($(OMM_DEV),-1)
  VERSION_CFLAGS += -DOMM_DEV=$(OMM_DEV)
  CUSTOM_C_DEFINES += -DOMM_DEV=$(OMM_DEV)
endif

# ---------
# Bug fixes
# ---------

NO_SKYBOX_TILES != sed -i 's/.*SKYCONV.*/\t@touch $$@/' Makefile.split

NO_MKZIP != : > tools/mkzip.py
